package com.marakosgrill.payment.dto;

import jakarta.validation.constraints.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDateTime;

@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class PaymentRequest {
    // Existing fields for compatibility
    private Long transactionId;
    @NotNull
    private Long reservationId;
    private LocalDateTime paymentDate;
    @NotBlank
    private String paymentMethod;
    @NotNull
    @DecimalMin("0.00")
    private BigDecimal amount;
    private Integer createdBy;
    
    // New fields for Culqi integration
    @NotBlank
    @Email
    private String customerEmail;
    
    @NotBlank
    private String customerName;
    
    @NotBlank
    private String customerPhone;
    
    // Culqi token generated by Culqi.js in frontend
    @NotBlank(message = "Culqi token is required")
    private String culqiToken;
    
    private String description;
}


